# Generated by Django 3.2.8 on 2021-11-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_auto_20211104_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_of_birth',
            field=models.IntegerField(db_index=True),
        ),
    ]
