# Generated by Django 3.2.8 on 2021-11-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0004_tvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='yamod.person'),
        ),
    ]
