# Generated by Django 3.2.8 on 2021-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0005_tvshow_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.IntegerField()),
            ],
        ),
    ]
