# Generated by Django 3.2.8 on 2021-11-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0006_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='yamod.tvshow'),
            preserve_default=False,
        ),
    ]
