# Generated by Django 3.2.8 on 2021-11-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0007_season_tv_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yamod.season')),
            ],
        ),
    ]
