# Generated by Django 3.2.8 on 2021-11-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0008_episode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('season_no', 'tv_show')},
        ),
    ]
