# Generated by Django 3.2.8 on 2021-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0010_create_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='cast',
            field=models.ManyToManyField(to='yamod.Person'),
        ),
    ]
