# Generated by Django 3.2.8 on 2021-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0011_season_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='original_title',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
